#MAINLOOP PHASES
PHASE_SETUP	= 			-1
PHASE_ROLL = 			0
PHASE_DEAL	= 			1
PHASE_BUILD_AND_TRADE= 	2
PHASE_END_TURN = 		3

#RESOURCE_TYPES
RESOURCE_DESERT	= -1
RESOURCE_SHEEP	= 0
RESOURCE_WHEAT	= 1
RESOURCE_ORE	= 2
RESOURCE_WOOD	= 3
RESOURCE_BRICK	= 4
RESOURCE_GOLD	= 5 #NYI

RESOURCES = [
	RESOURCE_SHEEP,
	RESOURCE_WHEAT,
	RESOURCE_ORE,
	RESOURCE_WOOD,
	RESOURCE_BRICK,
]

RESOURCE_TILES = [
	RESOURCE_SHEEP,
	RESOURCE_WHEAT,
	RESOURCE_ORE,
	RESOURCE_WOOD,
	RESOURCE_BRICK,
	RESOURCE_DESERT,
]

RESOURCE_MAP_INT_TO_NAME = {
	RESOURCE_SHEEP : "Wool",
	RESOURCE_WHEAT : "Wheat",
	RESOURCE_ORE : "Ore",
	RESOURCE_WOOD : "Wood",
	RESOURCE_BRICK : "Brick",
}

RESOURCE_MAP_INT_TO_COLOR = {
	RESOURCE_SHEEP : (70, 255, 70),
	RESOURCE_WHEAT : (230, 240, 0),
	RESOURCE_ORE : (120,120,120),
	RESOURCE_WOOD : (14, 140, 31),
	RESOURCE_BRICK : (255, 190, 110),
}

#RECIPES
RECIPE_KEY_ROAD			=0
RECIPE_KEY_SETTLEMENT	=1
RECIPE_KEY_CITY			=2
RECIPE_KEY_DEVELOPMENT	=3
RECIPES = {
	RECIPE_KEY_ROAD : {
		RESOURCE_WOOD 	: 1,
		RESOURCE_BRICK	: 1
	},
	RECIPE_KEY_SETTLEMENT : {
		RESOURCE_SHEEP	: 1,
		RESOURCE_WHEAT	: 1,
		RESOURCE_BRICK	: 1,
		RESOURCE_WOOD	: 1,
	},
	RECIPE_KEY_CITY : {
		RESOURCE_ORE 	: 3,
		RESOURCE_WHEAT	: 2,
	},
	RECIPE_KEY_DEVELOPMENT : {
		RESOURCE_SHEEP	: 1,
		RESOURCE_WHEAT	: 1,
		RESOURCE_ORE	: 1,
	},
}
RECIPE_MAP_INT_TO_NAME = {
	RECIPE_KEY_ROAD : "Road",
	RECIPE_KEY_SETTLEMENT : "Settlement",
	RECIPE_KEY_CITY : "City",
	RECIPE_KEY_DEVELOPMENT : "Development",
}

RESOURCE_MAP_NAME_TO_INT = {RESOURCE_MAP_INT_TO_NAME[k]:k for k in RESOURCE_MAP_INT_TO_NAME.keys()}

DEFAULT_EXCHANGE_RATES = {
	"*":4, #4 of any card, base trade
}

#BUILD PHASE OPTIONS
OPTION_CANCEL 			 = -1
OPTION_BUILD_ROAD		 = 1
OPTION_BUILD_SETTLEMENT	 = 2
OPTION_BUILD_CITY		 = 3
OPTION_BUILD_DEVELOPMENT = 4
OPTION_REQUEST_TRADE	 = 5
OPTION_END_TURN			 = 6

BUILD_PHASE_OPTIONS = [
	OPTION_BUILD_ROAD,
	OPTION_BUILD_SETTLEMENT,
	OPTION_BUILD_CITY,
	OPTION_BUILD_DEVELOPMENT,
	OPTION_REQUEST_TRADE,
	OPTION_END_TURN
]


#3-4 PLAYER DEFINITIONS
DEFAULT_PIECE_LIMITS_3_4 = {
	RECIPE_KEY_ROAD: 15,
	RECIPE_KEY_SETTLEMENT: 5,
	RECIPE_KEY_CITY: 4,
}

DEFAULT_TILE_COUNTS_3_4 = {
	RESOURCE_SHEEP : 4,
	RESOURCE_WHEAT : 4,
	RESOURCE_ORE : 3,
	RESOURCE_WOOD : 4,
	RESOURCE_BRICK : 3,
	RESOURCE_DESERT : 1,
}

DEFAULT_RESOURCE_CARD_COUNT_3_4 = {
	RESOURCE_SHEEP : 19,
	RESOURCE_WHEAT : 19,
	RESOURCE_ORE : 19,
	RESOURCE_WOOD : 19,
	RESOURCE_BRICK : 19,
}

DEFAULT_CHIT_COUNT_3_4 = {
	2:1,
	3:2,
	4:2,
	5:2,
	6:2,
	8:2,
	9:2,
	10:2,
	11:2,
	12:1,
}

# DEVELOPMENT_KNIGHT		:14,
# DEVELOPMENT_PROGRESS	:6,
# DEVELOPMENT_VICTORY		:5,

# DEFAULT_DEVELOPMENT_CARD_COUNT = {
# 	DEVELOPMENT_KNIGHT		:14,
# 	DEVELOPMENT_PROGRESS	:6,
# 	DEVELOPMENT_VICTORY		:5,
# }

# #5-6 PLAYER DEFINITIONS
# DEFAULT_TILE_COUNTS_5_6 = {
# 	RESOURCE_SHEEP : ,
# 	RESOURCE_WHEAT : ,
# 	RESOURCE_ORE : ,
# 	RESOURCE_WOOD : ,
# 	RESOURCE_BRICK : ,
# }

# DEFAULT_RESOURCE_CARD_COUNT_5_6 = {
# 	RESOURCE_SHEEP : ,
# 	RESOURCE_WHEAT : ,
# 	RESOURCE_ORE : ,
# 	RESOURCE_WOOD : ,
# 	RESOURCE_BRICK : ,
# }